@url = http://localhost:8080/api/deck

GET {{url}} HTTP/1.1

###

GET {{url}}/2 HTTP/1.1

###
# Create a new deck
POST {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "userId": 2,
  "deckName": "Http Deck Test"
}

###
# Update a deck, updatedAt should change as well
PUT {{url}}/4 HTTP/1.1
Content-Type: application/json

{
  "deckId": 4,
  "userId": 2,
  "deckName": "Http Deck Test Updated"
}

###

# Delete a deck
DELETE {{url}}/4 HTTP/1.1
